### ISSUE TITLE
Translation workflow

### ISSUE THREAD

**Issue by kuu** [html5rocks/updates.html5rocks.com.new#73]
I just want to translate `_posts/2015-01-21-ES6-Template-Strings.md` into Japanese.

For tutorials, each article has subdirectories for multiple locales.

But isn't there such automated i18n workflow for updates?

**Comment by kuu** [comment]
I did it in my [gist](https://gist.github.com/kuu/b7eb679a3ad48d980ed3).

**Comment by agektmr** [comment]
@devnook IIRC we don't support i18n on updates.h5r.com, correct?

**Comment by PaulKinlan** [comment]
Correct.

**Comment by agektmr** [comment]
@kuu I've posted on G+ and Twitter about your translation. Thanks a lot! In the meantime, you can send a PR that adds a link to your translation from the post.
