### ISSUE TITLE
RSS Feed out of date?

### ISSUE THREAD

**Issue by craigfrancis** [html5rocks/updates.html5rocks.com.new#74]
Can you check:

http://feeds.feedburner.com/html5rocks
http://updates.html5rocks.com/feeds/rss.xml

As the latest article it's showing is from December (How to use Service Worker), rather than Jan 20th (ES6 Template Strings).

Also the link in "/_includes/footer.html" goes to "/rss", which is a 404 :-)

**Comment by PaulKinlan** [comment]
Yep, they are two different sites.

I will look at /rss.

**Comment by jeffposnick** [comment]
As per http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fupdates.html5rocks.com%2Ffeeds%2Frss.xml there are issues with the `<link>` elements:

    line 97, column 53: link must be a full and valid URL: /2015/02/offline-first-with-sw-precache (10 occurrences) [help]
            <link>/2015/02/offline-first-with-sw-precache</link>

As well as a few other issues that also seem to be related to relative rather than absolute URLs.

I can take a look.

**Comment by jeffposnick** [comment]
This should be closed, as of https://github.com/html5rocks/updates.html5rocks.com.new/pull/85

**Comment by craigfrancis** [comment]
Thanks... working now :-)
